name: geo
version: 0.3.0
description: A set of functions and types usable in a geographic's context
homepage: https://github.com/a14n/dart-geo
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  test: ^1.16.8
  expector: ^0.1.2
