name: geo
version: 0.2.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A set of functions and types usable in a geographic's context
homepage: https://github.com/a14n/dart-geo
environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'
dependencies:
  meta: ^1.0.5
dev_dependencies:
  test: ^1.3.0
