name: geo
version: 0.1.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: "A set of geographic's functions"
homepage: https://github.com/a14n/dart-geo
dependencies:
  meta: ^1.0.5
dev_dependencies:
  test: ^0.12.4+1
