name: geo
version: 0.3.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A set of functions and types usable in a geographic's context
homepage: https://github.com/a14n/dart-geo
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  test: ^1.16.8
