name: geo
version: 0.0.1-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: "A set of geographic's functions"
homepage: https://github.com/a14n/dart-geo
dev_dependencies:
  unittest: any
